name: Deploy Streamlit App via Snowflake CLI

on:
  push:
    branches:
      - main

env:
  PYTHON_VERSION: '3.8'
  SNOWFLAKE_ACCOUNT: 'gp81875.west-europe.azure'
  SNOWFLAKE_USER: 'serah.jessica.mahendran@lumilinks.com'
  SNOWFLAKE_ROLE: 'DATA_SCIENTIST'
  SNOWFLAKE_DATABASE: 'DEV_DS'
  SNOWFLAKE_SCHEMA: 'DEV_JM'
  SNOWFLAKE_WAREHOUSE: 'COMPUTE_WH'

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install SnowSQL
        run: |
          curl -O https://sfc-repo.snowflakecomputing.com/snowsql/bootstrap/1.2/linux_x86_64/snowsql-1.2.24-linux_x86_64.bash
          chmod +x snowsql-1.2.24-linux_x86_64.bash
          ./snowsql-1.2.24-linux_x86_64.bash --prefix=$HOME/.snowsql
          echo "$HOME/.snowsql/bin" >> $GITHUB_PATH
          snowsql --version  # Check installation

      - name: Authenticate Snowflake using External Browser
        run: |
          snowsql -a ${{ env.SNOWFLAKE_ACCOUNT }} \
                  -u ${{ env.SNOWFLAKE_USER }} \
                  -r ${{ env.SNOWFLAKE_ROLE }} \
                  -d ${{ env.SNOWFLAKE_DATABASE }} \
                  -s ${{ env.SNOWFLAKE_SCHEMA }} \
                  --authenticator externalbrowser

      - name: Deploy Streamlit App to Snowflake
        run: |
          snow streamlit deploy --replace
